apiVersion: v1
kind: Service
metadata:
  name: tricentis-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: test-conductor
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: test-conductor
  type: LoadBalancer
---           
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-conductor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-conductor
  template:
    metadata:
      labels:
        app: test-conductor
    spec:
      containers:
<<<<<<< HEAD
      - image: agiletrailblazers.jfrog.io/demorepo/agiletrailblazers:latest
=======
      - image: 890882436612.dkr.ecr.us-east-2.amazonaws.com/test-conductor-java-8-pilot:latest
>>>>>>> 5864e8e54e7ed54265281ad0b2b903990e98642e
        imagePullPolicy: Always
        name: tricentis
        ports:
        - containerPort: 8080
          name: tricentis
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1"
          limits:
            memory: "4096Mi"
            cpu: "1"
      imagePullSecrets:
      - name: qtestjfrog
